### ISSUE TITLE
SoundManager Crashing iOS Simulator

### ISSUE THREAD

**Issue by andrewjaykeller** [nicklockwood/SoundManager#20]
Started working with Sound Manager this morning, and when running in the iOS Simulator (8.3, 8.4 and 9.0), a fatal crash is experienced on this line:
`[[SoundManager sharedManager] prepareToPlay];`

I am calling with 

```
 [SoundManager sharedManager].allowsBackgroundMusic  = YES;
 [SoundManager sharedManager].soundFadeDuration      = 1.0f;
 [[SoundManager sharedManager] prepareToPlay];
```

Crash is also occurring with 
`[[SoundManager sharedManager] prepareToPlayWithSound:[Sound soundNamed:kSISoundFXInitalize]];`

Stack Image:
<img width="360" alt="screenshot 2015-07-31 07 02 09" src="https://cloud.githubusercontent.com/assets/11437469/9006177/46a2377e-3752-11e5-963d-f372b7d8d840.png">

**Comment by nicklockwood** [comment]
Do you have break on exceptions enabled? If so, try disabling it. AVAudioPlayer throws C++ exceptions during normal use, so it may not actually be crashing, just hitting a breakpoint.

**Comment by andrewjaykeller** [comment]
Yes, that does fix the problem... any idea how to run the simulator with exception break point enabled for development?

**Comment by nicklockwood** [comment]
Yes, if you right-click on your breakpoint and select Edit, you can specify only Objective-C exceptions instead of All exceptions, then it won't break for the C++ exceptions thrown by AVAudioPlayer.

**Comment by andrewjaykeller** [comment]
Thanks! Maybe throw this in the README for other noob programers?
