### ISSUE TITLE
Pause possibility

### ISSUE THREAD

**Issue by nickgastaldi** [nicklockwood/SoundManager#3]
Hello nick,

any chance for a pause functionality (or a clue on how to do it)? 

or am i failling at finding a way to do so?

many thnx for the awesome job!

**Comment by nickgastaldi** [comment]
nevermind, initiating the same Sound file again works just like a play/pause function. :dart:

**Comment by nicklockwood** [comment]
Yes, sorry it wasn't very well documented. Hopefully this is now clearer.
