### ISSUE TITLE
Playing background audio doesn't work

### ISSUE THREAD

**Issue by xrksudy** [nicklockwood/SoundManager#8]
Hi:
   I download your code to do Playing background audio function. But I find a bug, when I set 

``` objc
[SoundManager sharedManager].allowsBackgroundMusic = YES;
```

But enter the background, the sound will stop play.

I search some article to solve this problem.You can refer to following articles.

[How to handle background audio playing while iOS device is locked or on another application](http://stackoverflow.com/questions/10429204/how-to-handle-background-audio-playing-while-ios-device-is-locked-or-on-another)
[IOS: Play sound in while app in background](http://stackoverflow.com/questions/16232315/ios-play-sound-in-while-app-in-background)

``` objc
I found your bug code:
- (void)setAllowsBackgroundMusic:(BOOL)allow
{
    if (_allowsBackgroundMusic != allow)
    {

#if TARGET_OS_IPHONE

        _allowsBackgroundMusic = allow;
        AVAudioSession *session = [AVAudioSession sharedInstance];
        [session setCategory:allow? AVAudioSessionCategorySoloAmbient: AVAudioSessionCategorySoloAmbient error:NULL];
#endif

    }
}
```

You should fix as follow:

``` objc
AVAudioSession *session = [AVAudioSession sharedInstance];
[session setCategory:allow? AVAudioSessionCategoryPlayback: AVAudioSessionCategorySoloAmbient error:NULL];
```

and in the plist file, add Required background modes key.

**Comment by nicklockwood** [comment]
This isn't a bug; the purpose of the allowsBackgroundMusic flag is not to allow SoundManager sounds to play when the app is in the background, it is to allow background music (such as the iPod) to continue to play in the background when SoundManager sounds are playing.

**Comment by nicklockwood** [comment]
Apologies, looking at the code I see that it is in fact incorrect, and your fix is valid. The intended behaviour is as I described though: it won't allow SoundManager to play audio when the app is in the background.

**Comment by nicklockwood** [comment]
No, I was right the first time. The code you pasted in your report doesn't match the code in the library. The value I am using when allowsBackgroundMusic is enabled is YES is AVAudioSessionCategoryAmbient, not AVAudioSessionCategorySoloAmbient - this is correct.

If you wish to use a different audio category, you can just set it yourself - it won't conflict with SoundManager.
